### ISSUE TITLE
Comparing Videos with Different Dimensions

### ISSUE THREAD

**Issue by Naeemh1** [svt/vivictpp#17]
Currently, when comparing two videos of different dimensions, the left is scaled to the dimensions of the right, making comparing 1920x800 videos with 1920x1080 (where the extra pixels are black bars) inconvenient.
Is there any way to avoid this scaling?

**Comment by grusell** [comment]
At the moment vivictpp assumes the input videos have the same aspect ratio. I will look into making it possible to support input videos with different aspect ratios in a better way.

**Comment by Gloster10** [comment]
@[Naeemh1](https://github.com/Naeemh1) Naeemh :  From  my side of you, it is a bit stupid from your side of view, to reflect on bit compare but do not reflect there is no bit compare possible any more if you change aspects.
Think about it  !

**Comment by grusell** [comment]
@Gloster10 Not sure I understand you correctly, are you saying there are no valid usecases for comparing videos of different resolutions?

**Comment by grusell** [comment]
Version 0.1.14 has now been released which supports using filter that changes video resolution. The problem described by this issue can then be handled by cropping away the letterboxing from the 1920x1080 video with a command similar to the below

```
vivictpp --left-filter=crop=1920:800:0:140 my_video_1920x1080.mp4 my_video_1920x800.mp4
```

**Comment by Gloster10** [comment]
Obviously you are right, I am sorry @Naeemh1 .
