### ISSUE TITLE
Error on file load

### ISSUE THREAD

**Issue by arthur-digby** [svt/vivictpp#9]
Using the Snap version (0.1.7) on Ubuntu. Trying to load 2 mkv video files. if I copy them in the home directory, loading works just fine. If I try to load them from another location (internal HDD) I get this error: "Vivict had an unexpected error: Failed to open input". I haven't managed to load any file from a location outside the home directory yet. I always receive this error.

In the Ubuntu Software manager the snap has a checkbox for permission to files in the home directory (it is on) but none for other locations. Could this be the reason files will not load? Is there any workaround besides copying all files in the home directory?

**Comment by grusell** [comment]
Yes, this is a problem/feature of snap I'm afraid. I can see how it would be annoying. For future builds I could add the https://snapcraft.io/docs/removable-media-interface, that would allow access to files under /media, /run/media and /mnt. Would that be useful in your case?

I see two options available right now for getting around the problem, besides the obvious solution of copying the files to your home directory:
* Build vivictpp from source, the built executable will not have the limitations imposed by snap.
* Install vivictpp from brew. I have to add though that personally I am not a fan of running brew on linux, so I would rather recommend building from source

**Comment by arthur-digby** [comment]
Thanks. Actually, most snap applications I have used have that option in the permissions for access to "removable media".  What it translates to is actually all locations you may have that are not in home. So, yes, that would solve the issue.

I'd like to try to build from source but I will have to do some more reading on this topic beforehand. I am a casual Ubuntu user and have a few attempts to building from source (other apps) but no success story yet. That's why, even though I do not prefer working with snaps in general, this would be the easier solution for me in this case. However, I will try to see if it is possible to build Vivictpp from source.

**Comment by grusell** [comment]
A new version, 0.1.10 has been released to the snap store. The snap now has the removable-media plug, but note that you will have to connect it manually. This can be done with the below command

`sudo snap connect vivictpp:removable-media :removable-media`

**Comment by arthur-digby** [comment]
Running that command in the terminal, I receive this message:

> error:` "vivictpp" has no plug named "removable-media"

**Comment by grusell** [comment]
Did you run `sudo snap refresh vivictpp` before to get the latest version?
You can check that you have the correct version of the snap by running
`snap info vivictpp` . Output should be similar to below, especially the row `installed:          v0.1.10            (5) 109MB -`

```
name:      vivictpp
summary:   Side-by-side/split-view video comparison tool
publisher: Gustav Grusell (grusell)
store-url: https://snapcraft.io/vivictpp
license:   GPL-2.0-or-later
description: |
  Side-by-side/split-view video comparison tool. See also https://github.com/svt/vivictpp
commands:
  - vivictpp.ffmpeg
  - vivictpp
snap-id:      6vIFO6CogbjNZ9Y4mt5jt4ZJnpuAYy4y
tracking:     latest/edge
refresh-date: yesterday at 21:38 CET
channels:
  latest/stable:    –                            
  latest/candidate: –                            
  latest/beta:      –                            
  latest/edge:      v0.1.10 2022-02-17 (5) 109MB -
installed:          v0.1.10            (5) 109MB -
```

**Comment by arthur-digby** [comment]
I did check the version in Ubuntu Software manager first. It said: v 0.1.10. Using the info command you provided, I am getting the same result as you. So it seems the version is right.

**Comment by grusell** [comment]
That is odd! What is the output if you run `snap connections vivictpp` to list the plugs of vivictpp?

**Comment by arthur-digby** [comment]
The command returns this:

```
Interface        Plug                      Slot             Notes
alsa             vivictpp:alsa             -                -
audio-playback   vivictpp:audio-playback   :audio-playback  -
home             vivictpp:home             :home            -
network          vivictpp:network          :network         -
opengl           vivictpp:opengl           :opengl          -
pulseaudio       vivictpp:pulseaudio       -                -
removable-media  vivictpp:removable-media  -                -
x11              vivictpp:x11              :x11             -
```

**Comment by arthur-digby** [comment]
Yes, that seems weird.

**Comment by arthur-digby** [comment]
For some weird reason, the checkbox for read/write on removable media has now appeared on the permissions dialog in the Vivictpp snap. It is the next day so perhaps all that was required was in fact a reboot after the update for the change to take effect.

Well, I guess we can close this bug now. Thank you! :)

**Comment by grusell** [comment]
Ah, good to hear :) .
